### PR TITLE
Adding Favicon & Social Media Buttons

### PR DESCRIPTION
**Pull request by johnathan99j**
Adding favicon found in my cache. I looked at the dev. icon and don't think it looks very good but then again that's probably due to my chrome theme.

### CODE REVIEW

**Comment by johnathan99j** [comment]
#28

**Comment by johnathan99j** [comment]
There we go, actual favicons.

**Comment by johnathan99j** [comment]
All tweaks done, ready to merge.

**Comment by johnathan99j** [comment]
Committed to the wrong branch, reverted.

**Comment by johnathan99j** [comment]
Hey @samozzy are you happy with these favicons ? I couldn't get any in decent resolution so took a logo and made these myself.

**Comment by samozzy** [comment]
**Favicon**
Is fine, but looks like it's been resized horizontally (the rings don't look circular). If you haven't done this and my eyes are failing me then by all means commit. If you have resized it to be square by changing its horizontal dimensions then I have an alternative file.

**Social buttons**
What's with the external CSS file? That sounds like a bad idea. Can I see a screenshot of your build with the buttons enabled? It shouldn't take much additional CSS to arrange the icons, then you just need the 2 pngs themselves. I don't understand why there's so much to that.

**Comment by johnathan99j** [comment]
**Social buttons**
The buttons live in the footer as shown bellow.
image

I've looked into them more and moved the css to be internal, it's from a project called Font Awesome and they allow you to use all [these](http://fortawesome.github.io/Font-Awesome/icons/) icons, and there vectors so can scale great.

**Favicon**
It has been resized slightly purely because none of the logos I have are perfectly square (aside from the tinsel one) but is that really noticeable for a favicon ? If you've got a square version then I'm happy to work with that instead.

**Comment by harry-bridge** [comment]
I have one somewhere that I put on the pulse of all things, I'll add it in
later when I'm not on the motorway.

**Comment by tomtom5152** [comment]
Take a look at AddThis, it's what I used on the dev site and I can get you
the api key if needed. Also, less issue reporting and driving Harry

On Sun, 31 Jan 2016 17:07 Harry Bridge notifications@github.com wrote:

> I have one somewhere that I put on the pulse of all things, I'll add it in
> later when I'm not on the motorway.
> 
> On Sunday, January 31, 2016, Johnathan Graydon notifications@github.com
> wrote:
> 
> > _Social buttons_
> > The buttons live in the footer as shown bellow.
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/15066398/12703398/0c658560-c83a-11e5-8e07-0be33bb7002d.png
> > 
> > I've looked into them more and moved the css to be internal, it's from a
> > project called Font Awesome and they allow you to use all these
> > http://fortawesome.github.io/Font-Awesome/icons/ icons, and there
> > vectors so can scale great.
> > 
> > _Favicon_
> > It has been resized slightly purely because none of the logos I have are
> > perfectly square (aside from the tinsel one) but is that really
> > noticeable
> > for a favicon ? If you've got a square version then I'm happy to work
> > with
> > that instead.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/nottinghamtec/Main-Website/pull/29#issuecomment-177551448
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nottinghamtec/Main-Website/pull/29#issuecomment-177551884
> .
> 
> ## 

Tom Price

**Comment by johnathan99j** [comment]
Their website details aren't very clear, from what I can gather AddThis puts our site into content recommendations on other sites that use AddThis right ?

**Comment by samozzy** [comment]
I like the AddThis buttons but not the things that intrude when I'm reading a site. I also think the social buttons should be central, left or right aligned, not in between as they are in your screenshot - but I do like them!
Perhaps having them on the home page around the phone and email area would work, and then smaller versions (say, 20-30px) immediately right of 'Legal' in the footer of just white logos (see http://blog.useiconic.com/assets/images/release-1.6-cover.png)

Square logo attached. 
square favicon I can't convert to *ico right now so I'll leave that to you.

**Comment by johnathan99j** [comment]
Here's two updated screenshots for the social buttons.
image
image

Also used your square image to update favicon.

**Comment by harry-bridge** [comment]
I've added some icons in but they're not showing up here for some reason

**Comment by johnathan99j** [comment]
I see them, there in a different branch. This thread is a pull request from my fork of the repo.

**Comment by pickleshb** [comment]
*sigh, *goes and hunts for his commits**

**Comment by harry-bridge** [comment]
_sigh_ if you could pull the stuff i've just done into here that would be great

**Comment by johnathan99j** [comment]
@pickleshb I'm afraid it seems to conflict with my branch and I don't know how to fix it since it's not showing where the conflicts are.

**Comment by harry-bridge** [comment]
Are you looking at it locally or on the github diff view?

**Comment by johnathan99j** [comment]
GitHub

**Comment by harry-bridge** [comment]
You'll have to look at it on your local copy to see the conflicts, the diff only shows what i've changed (remember to sync your local copy with the remote)

**Comment by johnathan99j** [comment]
Merged @pickleshb branch into pull request.

**Comment by harry-bridge** [comment]
Personally I prefer the footer icons like this, but that's just me
screen shot 2016-02-01 at 15 48 41

**Comment by samozzy** [comment]
I was wrong, it does look nicer after the copyright bit. Perhaps if the ones at the top could be white too, that'd be nice (to match the email and phone icons)

**Comment by johnathan99j** [comment]
Updated image for top of page, footer now matches Harry's
image

Not sure how I like favicon, as you can see it doesn't match my theme but that's just me, I prefer the one the forum has but obviously not with the rings chopped. Either way I'm happy to merge this now.

**Comment by samozzy** [comment]
favicon square white back
Present.

**Comment by tomtom5152** [comment]
I feel the icons get lost a little in the space as they are quite small. Whilst I quite like using a font file for this, 80 odd files seems a bit extreme for this. https://github.com/Templarian/MaterialDesign-Webfont provides a really nice alternative to this that is SCSS compatible and doesn't require yet another compiler. It is also compliant with the standard material design icons.

I'm not quite sure whats going on with your favicon, historically we always had one with white rings, and one with black rings, for public and members sites (can't remember which way around). In terms of making it look good with theming, we would need to add a non transparent background (maybe the accent colour of the logo we use), or just live with the fact that people with themes won't see it properly.

**Comment by johnathan99j** [comment]
I already have/made that icon just @pickleshb's set is different and certainly covers more basses and compatibly. It just comes down to what we want.

**Comment by harry-bridge** [comment]
I don't quite understand your comment about theming Tom, for browsers the icon is like the one for the members site but with a transparent background and then the grey icons are for peoples home screens and fits with the rigs theme.

**Comment by johnathan99j** [comment]
Icons updated into images.

**Comment by johnathan99j** [comment]
With no objections I'll merge this by the end of the day unless someone beats me to it.

**Comment by tomtom5152** [comment]
I object to the size of this merge, it is completely overinflated for what it needs to be.

**Comment by johnathan99j** [comment]
Aside from compatibility is there any reason to have a gazillion favicons @pickleshb ?

**Comment by harry-bridge** [comment]
:camel:

**Comment by harry-bridge** [comment]
Compatibility is the only reason though

**Comment by tomtom5152** [comment]
I feel this PR would best be targeted at another branch. I've merged it into a new branch on this repo for further work where everyone can push to.

**Comment by harry-bridge** [comment]
:+1:

**Pull request closed without merging**
