### PR TITLE
Updating committee

### LINKED ISSUE #75: Committee 17/18
Need to change the things.

### PR DESCRIPTION
**Pull request by nhyty**
Should close #75

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Tom needs more pixels, Harry needs more squareness

**Comment by tomtom5152** [comment]
I have the perfect number of pixels, renders at 160px, I have 162px

**Comment by tomtom5152** [comment]
Oh this failed because SU website, I had this fun with travis the other day.

**Comment by davidtaylorhq** [comment]
@tomtom5152 You have one quarter of the correct number of pixels :P #hidpi

**Comment by tomtom5152** [comment]
Oh shush, if you can find the original on smugmug somewhere you can have high DPI, I don't have it anymore.

In terms of fixing the build error, take this commit and apply it to this project (url will need changing) https://github.com/NottinghamSRN/NottinghamSRN/commit/8cb8cd6a58e99472faf080b2ade260b894c68ecd

**Comment by samozzy** [comment]
Some sentences literally don't make sense. Proof read before merging required.

**Pull request merged**
