### PR TITLE
Forum link in logo and footer

### LINKED ISSUE #41: Forum link
Where do we want this thing, in the footer and possibly somewhere else? Maybe?

### PR DESCRIPTION
**Pull request by harry-bridge**
would close #41 put the forum link in the footer (hidden on small devices) and when the logo is clicked on the landing page, I didn't like it in the drop down menu too much

### CODE REVIEW

**Comment by harry-bridge** [comment]
I got the impression they wanted the forum more than the members site, but can do

**Comment by davidtaylorhq** [comment]
@pickleshb Why not link to the actual members site? members.nottinghamtec.co.uk

**Comment by samozzy** [comment]
I don't know how much I like the logo being a link to the members site. While we could tell people, I don't think it's intuitive and I wonder if other visitors will click it by accident.
I agree that having members in the menu doesn't look great, but it might be the most intuitive for what people want.

**Comment by davidtaylorhq** [comment]
Crazy idea: how about having a special web address _just_ for members! That way clients can't get confused, and members have a quick way to get to where they want to go. Maybe something like members.nottinghamtec.co.uk ?

**Comment by samozzy** [comment]
@davidtaylorhq So. Much. Sass.
Let's go with the footer as the best compromise.

**Comment by davidtaylorhq** [comment]
I apologise for the sass ;)

I agree that having the logo as a link is un-intuitive. Footer sounds sensible to me.

**Comment by harry-bridge** [comment]
@davidtaylorhq oh god that sass it's unbearable, but ok shall remove the
one in the logo

**Comment by tomtom5152** [comment]
I agree a logo is a terrible idea, golden rule of links, make them look like links.

**Comment by tomtom5152** [comment]
How can we have so much discussion about a single link :camel:

**Comment by davidtaylorhq** [comment]
#bikeshedding

**Comment by harry-bridge** [comment]
Fixed it

**Comment by samozzy** [comment]
Gimme a sec, got a thing I want to add to this.

**Comment by harry-bridge** [comment]
To #bikeshed even further do we want &vert; as the separator or &boxv;

**Comment by samozzy** [comment]
@pickleshb Make it randomly decide on page load 😉

**Comment by wjdp** [comment]
This thread is a fantastic example of TEC in action

> because I like it thick

:yum:

**Comment by tomtom5152** [comment]
At the risk of this bikesheading any further, and the fact that for what is effectively one line, I'm going to merge this now

**Pull request merged**
