### PR TITLE
Splash video

### LINKED ISSUE #34: Full screen splash video
I've only just figured out how to do this hence why I'm only just suggesting it, but how would a full screen splash video on the homepage sound, sort of along the lines of http://www.gitkraken.com/

### PR DESCRIPTION
**Pull request by harry-bridge**
Have a splash video, would close #34, NO BIKESHEDDING!

### CODE REVIEW

**Comment by tomtom5152** [comment]
Have a screenshot!

Well timed screenshot

I really like what you have done with this, the video works perfectly and the whole experience feels smooth and works really well. The shadowing on the background looks really nice and the video covers the background as expected.

The file does not appear to be too obtuse but does not appear to be toaster quality, but it does not like slow connections at all (as expected), so I approve of the limiting to larger devices. I suspect it would look fugly on small screens anyway.

I'm very happy for this to be merged, if I could get a yes from another admin I would hit the button now _cough_ @davidtaylorhq _cough_

I feel the video could be improved in the future but that's a longer discussion for another time #bikesheding

**Comment by samozzy** [comment]
@tomtom5152 I'm not mega keen on the timelapse or "those who can't teach" parts of the video, and vastly prefer the parallax and photo slideshow part, but w/e.

**Comment by harry-bridge** [comment]
Yeah It loads rather slowly sometimes, that's why the previous splash image loads behind it first, was torn whether it should load the first frame as a static image first, but decided against it

**Comment by tomtom5152** [comment]
@samozzy I agree that those parts of the video are not fantastic, as it was not designed for this purpose, but it does the job and is a simple change later. 

The decision now is merge with the video as it stands now and update it later to exclude the time lapses, or close the PR for now and change the video and open a new one?

@pickleshb I agree the old placeholder works best, maybe if it's possible to add a check to see if it's loaded and fade the placeholder out, but that should be a further PR

**Comment by harry-bridge** [comment]
I could edit it tomorrow with relative ease and re-upload it somewhere

**Comment by tomtom5152** [comment]
@pickleshb just stick another one in smugmug in a folder somewhere ready to go and change the URL in the source.

Question now is, do we want the other one live overnight or do we wait?

**Comment by harry-bridge** [comment]
@tomtom5152 yeep, and I say we wait just a tad till we have a video we're all happy with

**Comment by tomtom5152** [comment]
:camel:

**Comment by harry-bridge** [comment]
If you don't want to build this locally to have a look, the updated video can be found [here](https://nottinghamtec.smugmug.com/Reference/Random-Tec-Stuff/i-dmq5Z5C/A).

**Comment by tomtom5152** [comment]
Is it just the exact same video with the time lapses cropped out?

**Comment by harry-bridge** [comment]
@tomtom5152 Yes

**Comment by tomtom5152** [comment]
@pickleshb Merge away then

**Pull request merged**
