### PR TITLE
Make youtube video autoplay on page load

### PR DESCRIPTION
**Pull request by harry-bridge**
Thought it may be something nice to autoplay the video muted, I doubt many people have actually clicked the play button

### CODE REVIEW

**Comment by samozzy** [comment]
Can it be muted?

**Comment by harry-bridge** [comment]
Yes, the `onPlayerReady(event)` function handles this so when the player has been loaded fully it then runs `event.target.mute()` which mutes the player

**Comment by nhyty** [comment]
I disagree with this, the most annoying thing, especially when on mobile devices, are autoplaying video

**Comment by tomtom5152** [comment]
I agree with @nhyty that this is a terrible idea, especially given #34 provides the same facility with much better styling.

**Comment by samozzy** [comment]
@pickleshb Did you look at making a media query for this to make it desktop-only while we sort out #34?

**Comment by harry-bridge** [comment]
Yeah it would be trivial to do in javascript, I never did it because we decided to abandon this idea

**Pull request closed without merging**
