### PR TITLE
Services

### PR DESCRIPTION
**Pull request by tomtom5152**
Made a good start at solving #12 but still quite a bit to do by copying things over from the dev site. This is what I believe there is so far:
- [x] Sound
- [x] PA
- [x] Amps
- [x] Multicores
- [x] Sound Control
- [x] Lighting
- [x] Generics
- [x] Intels
- [x] Effects
- [x] Lighting Control
- [x] AV
- [x] Projection
- [x] Playback

Many of the titles may need to be changed/removed to make the page a bit more compact. Don't really want to branch out onto multiple pages for this as it just isn't needed.

### CODE REVIEW

**Comment by samozzy** [comment]
I think it should all be one page. Maybe some "see more" options where the page expands, rather than many pages?
I don't know how much technical detail we should go for.

**Comment by johnathan99j** [comment]
I feel that "Sound Services" and "Lighting Services" are good section headings but they barely stand out from the other headings. I didn't event realise they were a different size till I checked.

**Comment by samozzy** [comment]
I think it should be like the contact page, with very large headings and navigation on the right-hand side.

**Comment by Jason-TEC** [comment]
I see it has been a while since this discussion was last active, however the events team would like us to be able to have rough 'packages' in both sound and lighting that internal groups can get an understanding of what we can actually provide. 
Attached is a rough idea of what I was thinking.
[Packages.docx](https://github.com/nottinghamtec/Main-Website/files/2343295/Packages.docx)

How do we go about making this happen?

**Comment by tomtom5152** [comment]
@Jason-TEC And the wheel spins again 😜

**Comment by Jason-TEC** [comment]
Is there a particular reason why this hasn't happened or just time?

**Comment by harry-bridge** [comment]
@Jason-TEC It needs proper work, either we do it properly a la hawthorn or not at all

**Comment by Jason-TEC** [comment]
Yeah thats fair enough, my idea was that we can have the package with a photo alongside of an event we have done with roughly that package.
Do that for each one then at the bottom have a range of things you could have with any of them i.e. DJ kit, staging etc...

**Comment by jonnygate** [comment]
Why are we having this discussion here?? Surely before uploading it to any website we should decide whether it’s actually a good idea or not on the actual forum machine?

**Pull request closed without merging**
