### PR TITLE
Fixed hugo version

### LINKED ISSUE #65: Pages attempting to link as .html
Subpages 404-ing as all links are attempting to be *.html

### PR DESCRIPTION
**Pull request by harry-bridge**
Hopefully this fixes #65 and #62

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
If we can revert commit 2ff08e9 then I'd be happy. @wjdp is this a bug in htmltest? 

We have CheckInternalHash: false, so I feel like it should ignore all links starting with a hash

**Comment by harry-bridge** [comment]
Feel free however I assure you it will fail

**Comment by wjdp** [comment]
@davidtaylorhq Not a bug, just currently isn't an option to turn the check off — https://github.com/wjdp/htmltest/issues/30

**Comment by davidtaylorhq** [comment]
Ok, sounds good, we can revert the commit once the option is added to htmltest :)

Mergy mergy time

**Pull request merged**
