### PR TITLE
Favicon social

### LINKED ISSUE #28: Favicon
Currently missing. Should be added

### PR DESCRIPTION
**Pull request by harry-bridge**
Would close #28

### CODE REVIEW

**Comment by tomtom5152** [comment]
Can we have a screenshot of the social icons please.

**Comment by harry-bridge** [comment]
one sec

**Comment by wjdp** [comment]
That's an awful lot of commits to add a favicon.

**Comment by harry-bridge** [comment]
**Header**
screen shot 2016-02-02 at 16 41 32
**Footer**
screen shot 2016-02-02 at 16 41 47

**Comment by samozzy** [comment]
So many files.

**Pull request merged**
