### PR TITLE
Ross wanted a new picture, this is it

### PR DESCRIPTION
**Pull request by harry-bridge**

### CODE REVIEW

**Comment by wjdp** [comment]
Just noted you've needed to turn `sudo` on, was this just because the SU's website's SSL borks with old curl?

Wondering if checking SU exists is worth the slower builds :stuck_out_tongue:

**Comment by tomtom5152** [comment]
That snuck through, very interested to know the reason though

**Comment by harry-bridge** [comment]
@tomtom5152 Will wins the points, it doesn't make builds that much slower checking them and

**Comment by harry-bridge** [comment]
@tomtom5152 Bloody telegram, that's what html proofed is there for, although on the other hand could just as easily ignore them

**Pull request merged**
