### PR TITLE
Added new committee

### LINKED ISSUE #36: New committee
Uhoh.

### PR DESCRIPTION
**Pull request by harry-bridge**
Added the new committee members in, someone may want to re-do the bios before it's made live, would close #36 

:camel:

### CODE REVIEW

**Comment by wjdp** [comment]
:shipit:, :shipit: now

this made me blow air out of my nose

**Comment by tomtom5152** [comment]
Bravo sir, bravo. 

On a more serious note, would it be better to code the photos as a for loop and an array so it works for any size position. A fringe case I know but still.

**Comment by harry-bridge** [comment]
Yes it would be good and proper, however any more than 2 photos and it starts to look a bit messy, I don't think there will be more than two people running in slate anytime soon.

**Comment by tomtom5152** [comment]
Fair enough, it was just a thought, might be a nice way to deal with
multiple people rather than photo and photo2 though.

**Comment by harry-bridge** [comment]
Yeah, it was a quick and dirty way to do it, it's now done loopy style

**Comment by tomtom5152** [comment]
@samozzy can we potentially get some better word things please?

**Comment by harry-bridge** [comment]
I'm happy to merge this now :camel:

**Pull request merged**
